# Generated by Django 2.2.4 on 2019-08-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('user_agent', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_api.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_api.BrowserInstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_api.Question')),
            ],
        ),
    ]
