# Generated by Django 2.2.4 on 2019-08-22 22:31

from django.db import migrations, models
import polls_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='url',
            field=models.TextField(default=polls_api.models.create_url, unique=True),
        ),
    ]
