# Generated by Django 2.2.4 on 2019-08-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0002_remove_poll_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='polloption',
            old_name='name',
            new_name='title',
        ),
    ]
