# Generated by Django 2.2.4 on 2019-08-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0003_poll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
