# Generated by Django 2.2.4 on 2019-08-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0004_auto_20190822_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresponse',
            name='browser_instance',
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='ip',
            field=models.TextField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='user_agent',
            field=models.TextField(default='user agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls_api.Poll'),
        ),
    ]
