# Generated by Django 2.2.4 on 2019-08-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0005_auto_20190823_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponse',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='polls_api.PollOption'),
        ),
    ]
