# Generated by Django 2.2.4 on 2019-08-24 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0006_auto_20190824_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
